version: '3'

services:
  page_analyzer:
    build: .
    container_name: page_analyzer
    command: make start
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@page_analyzer_pgdb:5432/postgres
    volumes:
      - .:/python-project-83
    depends_on:
      - page_analyzer_pgdb


  page_analyzer_pgdb:
    image: postgres
    container_name: page_analyzer_pgdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
#      - ./pgdata:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/001.sql
    ports:
      - "5001:5432"
